x-common: &common-setup
  image: fabook/champ:v0.0.5
  network_mode: host
  privileged: true
  volumes:
    - ${HOME}/.Xauthority:/home/mobile/.Xauthority:rw
    - .:/home/mobile/ros2_ws/src:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /dev/dri:/dev/dri:rw
  environment:
    - DISPLAY
    - QT_X11_NO_MITSHM=1
  working_dir: /home/mobile/ros2_ws


services:
  terminal-local:
    image: fabook/champ:v0.0.5
    <<: *common-setup
    stdin_open: true  # dsocker run -i
    tty: true        # docker run -t
    command: []
  
  terminal:
    image: fabook/champ:<TBA>
    <<: *common-setup
    stdin_open: true  # dsocker run -i
    tty: true        # docker run -t
    command: []