x-common: &common-setup
  image: fabook/champ:v0.0.5
  network_mode: host
  privileged: true
  volumes:
    - ${HOME}/.Xauthority:/home/mobile/.Xauthority:rw
    - .:/home/mobile/ros2_ws/src:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /dev/dri:/dev/dri:rw
  environment:
    - DISPLAY
    - QT_X11_NO_MITSHM=1
  working_dir: /home/mobile/ros2_ws


services:
  terminal:
    environment:
    - TELEMETRY_PROTO=udp   # <-- was PROTO=tcp (unused). Use the var your node reads.
    - TEL_HOST=0.0.0.0      # <-- bind wildcard, receives from host
    - TEL_PORT=5600
    image: fabook/champ:v0.0.5
    <<: *common-setup
    stdin_open: true  # dsocker run -i
    tty: true        # docker run -t
    command: []
  
  terminal-rpi:
    image: fabook/champ:rpi-v0.0.1
    <<: *common-setup
    stdin_open: true  # dsocker run -i
    tty: true        # docker run -t
    command: [
      "/bin/bash","-lc","
      sudo chmod 666 /dev/ttyUSB* 2>/dev/null || true &&
      sudo chmod 666 /dev/ttyACM* 2>/dev/null || true;
      exec bash"
      ]
