ekf_odom:
  ros__parameters:
    frequency: 60.0
    two_d_mode: true
    publish_tf: true

    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # IMU: только yaw и wyaw
    imu0: /imu/data
    imu0_config:  [false,false,false,
                   false,false,true,
                   false,false,false,
                   false,false,true,
                   false,false,false]
    imu0_remove_gravitational_acceleration: false
    imu0_nodelay: true
    imu0_queue_size: 20

    odom0: /lidar/odom
    odom0_config: [true, true,  false,
                   false,false, false,
                   true,  false, false,
                   false, false, false,
                   false, false, false]
    odom0_differential: true       
    odom0_relative: false
    odom0_nodelay: true
    odom0_queue_size: 5
    odom0_pose_rejection_threshold: 5.0 
    odom0_twist_rejection_threshold: 5.0

    # ===== 15x15 process_noise_covariance (row-major) =====
    process_noise_covariance: [
    # x     y     z     roll  pitch yaw   vx     vy     vz    vroll vpitch vyaw  ax    ay    az
      0.10, 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0  , 0.0  , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0,
      0.0 , 0.10, 0.0 , 0.0 , 0.0 , 0.0 , 0.0  , 0.0  , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0,
      0.0 , 0.0 , 0.06, 0.0 , 0.0 , 0.0 , 0.0  , 0.0  , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0,
      0.0 , 0.0 , 0.0 , 0.03, 0.0 , 0.0 , 0.0  , 0.0  , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0,
      0.0 , 0.0 , 0.0 , 0.0 , 0.03, 0.0 , 0.0  , 0.0  , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0,
      0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.06, 0.0  , 0.0  , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0,
      0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.05 , 0.0  , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0,
      0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0  , 0.05 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0,
      0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0  , 0.0  , 0.04, 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0,
      0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0  , 0.0  , 0.0 , 0.01, 0.0 , 0.0 , 0.0 , 0.0 , 0.0,
      0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0  , 0.0  , 0.0 , 0.0 , 0.01, 0.0 , 0.0 , 0.0 , 0.0,
      0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0  , 0.0  , 0.0 , 0.0 , 0.0 , 0.02, 0.0 , 0.0 , 0.0,
      0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0  , 0.0  , 0.0 , 0.0 , 0.0 , 0.0 , 0.05, 0.0 , 0.0,
      0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0  , 0.0  , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.05, 0.0,
      0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0  , 0.0  , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.07
    ]


    print_diagnostics: true
